title: Сергей Садчиков | DevOps Engineer
description: Портфолио и техническая документация. Platform Engineering, CI/CD, IaC, Kubernetes.
url: "https://sadchikovsg.github.io"
baseurl: "" 

remote_theme: pmarsceill/just-the-docs

color_scheme: dark

search_enabled: true
heading_anchors: true

mermaid:
  version: "9.4.3"

favicon_ico: "/favicon.ico"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
